# Generated by Django 2.1.3 on 2018-11-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='stars',
            field=models.IntegerField(default=1),
        ),
    ]
