# Generated by Django 2.1.3 on 2018-11-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20181130_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='stars',
            field=models.IntegerField(default=1, help_text='select 1-5 to rate'),
        ),
    ]
