# Generated by Django 2.1.3 on 2018-11-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20181130_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='storeaddress',
            field=models.CharField(max_length=200),
        ),
    ]
